const char HTML_BODY[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "  <meta charset='UTF-8'>\n"
    "  <title>Sistema de Controle de Nível de Água</title>\n"
    "  <style>\n"
    "    body { font-family: sans-serif; text-align: center; padding: 10px; margin: 0; background: #f9f9f9; }\n"
    "    .botao { font-size: 18px; padding: 8px 20px; margin: 5px; border: none; border-radius: 8px; cursor: pointer; background: #dbdbdb ; }\n"
    "    .campo-config { margin: 10px 0; }\n"
    "    .campo-config input { width: 60px; padding: 4px; font-size: 16px; }\n"
    "    .label { font-weight: bold; margin-bottom: 5px; display: block; }\n"
    "    .barra { width: 50%; background: #ddd; border-radius: 6px; overflow: hidden; margin: 0 auto 15px auto; height: 25px; }\n"
    "    .preenchimento { height: 100%; transition: width 0.3s ease; background: #2196F3; }\n"
    "    @media (max-width: 600px) {\n"
    "      .barra { width: 80%; }\n"
    "      .botao, .campo-config input { width: 80%; }\n"
    "    }\n"
    "  </style>\n"
    "  <script>\n"
    "    function updateLimits() {\n"
    "      const min = document.getElementById('input-min').value;\n"
    "      const max = document.getElementById('input-max').value;\n"
    "      fetch(`/config?min=${min}&max=${max}`)\n"
    "        .then(res => {\n"
    "          if (!res.ok) alert('Falha ao atualizar limites!');\n"
    "          return res.json();\n"
    "        })\n"
    "        .then(data => {\n"
    "          document.getElementById('limite-min').innerText = data.min;\n"
    "          document.getElementById('limite-max').innerText = data.max;\n"
    "        })\n"
    "        .catch(err => console.error(err));\n"
    "    }\n"
    "\n"
    "    function atualizar() {\n"
    "      fetch('/estado')\n"
    "        .then(res => res.json())\n"
    "        .then(data => {\n"
    "          document.getElementById('nivel-valor').innerText = data.level;\n"
    "          const pct = Math.min(100, Math.max(0, Math.round(data.level / data.max * 100)));\n"
    "          document.querySelector('.preenchimento').style.width = pct + '%';\n"
    "          const pumpEl = document.getElementById('pump-state');\n"
    "          pumpEl.innerText = data.pump ? 'Ligada' : 'Desligada';\n"
    "          pumpEl.className = data.pump ? 'on' : 'off';\n"
    "          document.getElementById('limite-min').innerText = data.min;\n"
    "          document.getElementById('limite-max').innerText = data.max;\n"
    "        })\n"
    "        .catch(err => console.error(err));\n"
    "    }\n"
    "    setInterval(atualizar, 1000);\n"
    "    window.onload = atualizar;\n"
    "  </script>\n"
    "</head>\n"
    "<body>\n"
    "  <h1>Sistema de Controle de Nível de Água</h1>\n"
    "  <p class='label'>Nível Atual: <span id='nivel-valor'>--</span></p>\n"
    "  <div class='barra'><div class='preenchimento'></div></div>\n"
    "  <p class='label'>Bomba: <span id='pump-state'>--</span></p>\n"
    "  <hr style='margin: 20px 0;'>\n"
    "  <div class='campo-config'>\n"
    "    <label class='label'>Limite Mínimo Atual: <span id='limite-min'>--</span></label>\n"
    "    Novo limite: <input type='number' id='input-min' min='0' max='100' step='1'>\n"
    "  </div>\n"
    "  <div class='campo-config'>\n"
    "    <label class='label'>Limite Máximo Atual: <span id='limite-max'>--</span></label>\n"
    "    Novo limite: <input type='number' id='input-max' min='1' max='100' step='1'>\n"
    "  </div>\n"
    "  <button class='botao' onclick='updateLimits()'>Atualizar Limites</button>\n"
    "  <p style='font-size: 14px; color: #666; margin-top: 30px;'>\n"
    "    Sistema de controle de nível - EmbarcaTech\n"
    "  </p>\n"
    "</body>\n"
    "</html>\n";
